name: Issue Management
on:
  pull_request:
    types: [opened, reopened]
jobs:
  add-to-project:
    name: Add pull request to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@main
        with:
          project-url: https://github.com/orgs/pds-data-dictionaries/projects/3
          github-token: ${{ secrets.ADMIN_GITHUB_TOKEN }}

